"""empty message

Revision ID: 3f7d39230a59
Revises: 1675f68caf3e
Create Date: 2018-02-08 22:23:25.839769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7d39230a59'
down_revision = '1675f68caf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profile', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Profile', 'Users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Profile', type_='foreignkey')
    op.drop_column('Profile', 'userId')
    # ### end Alembic commands ###
