"""empty message

Revision ID: ffbbd1be8b4f
Revises: bb8428c4f355
Create Date: 2018-02-08 22:16:47.475793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbbd1be8b4f'
down_revision = 'bb8428c4f355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Profile_id_seq"\'::regclass)'), nullable=False),
    sa.Column('host', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('port', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Profile_pkey')
    )
    # ### end Alembic commands ###
